version: '3.8'

services:
  restaurant-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PLACES_API_KEY=${PLACES_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - restaurant-network

  # PostgreSQL database (for future use based on todo.md)
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - restaurant-network

  # Redis for caching (mentioned in todo.md)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - restaurant-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  restaurant-network:
    driver: bridge
